---
abstract: 'analyse perl memory usage'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  ExtUtils::CBuilder: 0
  Test::Identity: 0
  Test::More: 0.88
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-MAT
provides:
  Devel::MAT:
    file: lib/Devel/MAT.pm
    version: 0.11
  Devel::MAT::Context:
    file: lib/Devel/MAT/Context.pm
    version: 0.11
  Devel::MAT::Context::EVAL:
    file: lib/Devel/MAT/Context.pm
    version: 0.11
  Devel::MAT::Context::SUB:
    file: lib/Devel/MAT/Context.pm
    version: 0.11
  Devel::MAT::Context::TRY:
    file: lib/Devel/MAT/Context.pm
    version: 0.11
  Devel::MAT::Dumper:
    file: lib/Devel/MAT/Dumper.pm
    version: 0.11
  Devel::MAT::Dumpfile:
    file: lib/Devel/MAT/Dumpfile.pm
    version: 0.11
  Devel::MAT::SV:
    file: lib/Devel/MAT/SV.pm
    version: 0.11
  Devel::MAT::SV::ARRAY:
    file: lib/Devel/MAT/SV.pm
    version: 0.11
  Devel::MAT::SV::CODE:
    file: lib/Devel/MAT/SV.pm
    version: 0.11
  Devel::MAT::SV::FORMAT:
    file: lib/Devel/MAT/SV.pm
    version: 0.11
  Devel::MAT::SV::GLOB:
    file: lib/Devel/MAT/SV.pm
    version: 0.11
  Devel::MAT::SV::HASH:
    file: lib/Devel/MAT/SV.pm
    version: 0.11
  Devel::MAT::SV::INVLIST:
    file: lib/Devel/MAT/SV.pm
    version: 0.11
  Devel::MAT::SV::IO:
    file: lib/Devel/MAT/SV.pm
    version: 0.11
  Devel::MAT::SV::Immortal:
    file: lib/Devel/MAT/SV.pm
    version: 0.11
  Devel::MAT::SV::LVALUE:
    file: lib/Devel/MAT/SV.pm
    version: 0.11
  Devel::MAT::SV::NO:
    file: lib/Devel/MAT/SV.pm
    version: 0.11
  Devel::MAT::SV::REF:
    file: lib/Devel/MAT/SV.pm
    version: 0.11
  Devel::MAT::SV::REGEXP:
    file: lib/Devel/MAT/SV.pm
    version: 0.11
  Devel::MAT::SV::SCALAR:
    file: lib/Devel/MAT/SV.pm
    version: 0.11
  Devel::MAT::SV::STASH:
    file: lib/Devel/MAT/SV.pm
    version: 0.11
  Devel::MAT::SV::UNDEF:
    file: lib/Devel/MAT/SV.pm
    version: 0.11
  Devel::MAT::SV::Unknown:
    file: lib/Devel/MAT/SV.pm
    version: 0.11
  Devel::MAT::SV::YES:
    file: lib/Devel/MAT/SV.pm
    version: 0.11
  Devel::MAT::Tool::Count:
    file: lib/Devel/MAT/Tool/Count.pm
    version: 0.11
  Devel::MAT::Tool::Inrefs:
    file: lib/Devel/MAT/Tool/Inrefs.pm
    version: 0.11
  Devel::MAT::Tool::Reachability:
    file: lib/Devel/MAT/Tool/Reachability.pm
    version: 0.11
requires:
  File::ShareDir: 1.00
  List::Util: 1.29
  Module::Pluggable: 0
  perl: 5.010
resources:
  license: http://dev.perl.org/licenses/
version: 0.11
