---
abstract: 'write a heap dump file for later analysis'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  ExtUtils::CBuilder: 0
  Test::Identity: 0
  Test::More: 0.88
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132661'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-MAT
provides:
  Devel::MAT::Dumper:
    file: lib/Devel/MAT/Dumper.pm
    version: 0.05
  Devel::MAT::Dumpfile:
    file: lib/Devel/MAT/Dumpfile.pm
    version: 0.05
  Devel::MAT::SV:
    file: lib/Devel/MAT/SV.pm
    version: 0.05
  Devel::MAT::SV::ARRAY:
    file: lib/Devel/MAT/SV.pm
  Devel::MAT::SV::CODE:
    file: lib/Devel/MAT/SV.pm
  Devel::MAT::SV::FORMAT:
    file: lib/Devel/MAT/SV.pm
  Devel::MAT::SV::GLOB:
    file: lib/Devel/MAT/SV.pm
  Devel::MAT::SV::HASH:
    file: lib/Devel/MAT/SV.pm
  Devel::MAT::SV::IO:
    file: lib/Devel/MAT/SV.pm
  Devel::MAT::SV::Immortal:
    file: lib/Devel/MAT/SV.pm
  Devel::MAT::SV::LVALUE:
    file: lib/Devel/MAT/SV.pm
  Devel::MAT::SV::NO:
    file: lib/Devel/MAT/SV.pm
  Devel::MAT::SV::REGEXP:
    file: lib/Devel/MAT/SV.pm
  Devel::MAT::SV::SCALAR:
    file: lib/Devel/MAT/SV.pm
  Devel::MAT::SV::STASH:
    file: lib/Devel/MAT/SV.pm
  Devel::MAT::SV::UNDEF:
    file: lib/Devel/MAT/SV.pm
  Devel::MAT::SV::Unknown:
    file: lib/Devel/MAT/SV.pm
  Devel::MAT::SV::YES:
    file: lib/Devel/MAT/SV.pm
requires:
  List::Util: 1.29
  perl: 5.012
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
